### PR TITLE
pull prescat data for mapping

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@mcohenui hi Mychal could you look at the program "Pull additional public housing information for mapping" and let me know if it makes sense that there's no subsidized projects for stanton commons ? (tract 74.6, 74.7, 74.8, 75.2, and 75.4.)

**Comment by maggiesu0725** [comment]
@mcohenui could you take a look at the program Pull additional public housing information for mapping and let me know if it makes sense that there's no subsidized projects for Stanton commons? Thanks

**Comment by mcohenui** [comment]
@maggiesu0725 it doesn't make sense. I think your census tracts are missing a digit.

**Comment by maggiesu0725** [comment]
@rpitingolo could you take a look at the program "compile block level data for mapping" and let me know why there are more than one observation for each blockgroup for 2010 census data?

**Pull request merged**
